version: '3.8'

services:
  nginx-42:
    build: ./requirements/nginx
    image: nginx-42
    container_name: nginx-42
    ports:
      - 443:443
    depends_on:
      - wordpress-site
    volumes:
      - wordvol:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb-data:
    build: ./requirements/mariadb
    image: mariadb-data
    container_name: mariadb-data
    env_file:
      - .env
    volumes:
      - mariavol:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
  
  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file:
      - .env
    depends_on:
      mariadb-data:
        condition: service_healthy
    volumes:
      - wordvol:/var/www/html
    networks:
      - inception
    restart: on-failure


volumes:
  mariavol:
    name: mariavol
    driver_opts:
      type: none
      device: /home/lleiria-/data/mysql
      o: bind
  wordvol:
    name: wordvol
    driver_opts:
      type: none
      device: /home/lleiria-/data/wordpress
      o: bind

networks:
  inception:
    name: inception